[package]
name = "telegram_bot"
version = "0.1.1"
edition = "2021"


[dependencies]
dotenvy = "0.15.7"
teloxide = "0.12.2"
tokio = {version="1.8", features=["rt-multi-thread", "macros"]}
log = "0.4"
pretty_env_logger = "0.5.0"
reqwest = "0.11.23"
serde_json = "1.0.111"
